version: '3.1'
services:
  # This is deployed to Google Cloud Artifact Repository
  # app:
  #   image: asia-southeast2-docker.pkg.dev/mystical-atlas-409504/techworld-app-express-mongo/techworld-app-express-mongo:1.0.1
  #   restart: always
  #   ports:
  #     - 3000:3000
  mongo:
    image: mongo
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
volumes:
  mongo-data:
    driver: local
